name: Daily Market Data Fetch

on:
  schedule:
    - cron: '0 9 * * *'  # Scheduled to run daily at 9 AM UTC
  workflow_dispatch:       # Enables manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Correct version

      - name: Clear pip cache
        run: pip cache purge  # Optional but clears cache for fresh run

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute run.py
        run: python src/run.py
